### ISSUE TITLE
Architecture: Defining the article-crawler pipeline

### ISSUE THREAD

**Issue by lwm** [WorldBrain/cortex#1]
1) The crawler accepts requests with a domain
2) The crawler creates a [celery web worker][worker] to deal with this request and returns HTTP 200.
3) The crawler fires a HTTP GET to retrieve the `robots.txt` of the domain
4) If the robots file is there, we try to obey it during our crawl, otherwise, we use our defaults
5) Crawl domain and parse data
6) Index data in the database

This seems to be a standard way to go. Check this [wikipedia section][arch]. I will also read [this paper][dev] in the coming days to get more acquainted with the scope of this.

Celery is a very mature asynchronous python library. The worker has all the things we need (from my brief review of the above paper): retries, time outs, rate limiting, queuing, etc. Step 2 means we can accept as many requests as we have computing power to run workers.

If at some point, the parsing of the data fails in step 5, we log the traceback / error and fail the task. We watch the logs, find out the reason, adapt and improve.

I imagine that the crawler and the workers are going to be running in seperate [docker] containers.

Thoughts?

[worker]: http://docs.celeryproject.org/en/latest/userguide/workers.html
[docker]: https://www.docker.com/
[arch]: https://en.wikipedia.org/wiki/Web_crawler#Architectures
[dev]: http://cis.poly.edu/tr/tr-cis-2001-03.pdf

**Comment by oliversauter** [comment]
@lwm 

> 4) If the robots file is there, we try to obey it during our crawl, otherwise, we use our defaults
What is our defaults then?

**Comment by lwm** [comment]
> What is our defaults then?

Probably just crawl everything and choose a suitable `crawl-delay`.

Ref: https://en.wikipedia.org/wiki/Robots_exclusion_standard#Nonstandard_extensions

[1]: http://www.google.com/robots.txt

**Comment by lwm** [comment]
This is a dupe of https://github.com/WorldBrain/Webmarks/issues/14.

**Comment by oliversauter** [comment]
Found another free content parser: https://www.readability.com/developers/api/parser

But has api cap.

**Comment by dev-tim** [comment]
Hm, good. So we are going to use celery as Scheduler for py workers, @lwm what would be your thought about results storage. 

I'd pick something document-oriented so we don't bother ourselves with schema and then we feed it to the search.

Did you work with celery before? I got some experience, but it was rather sad. For our context it should work.

**Comment by lwm** [comment]
> @lwm what would be your thought about results storage.

No idea. The search people will hopefully educate me there. We need to define that interface together.

> I'd pick something document-oriented so we don't bother ourselves with schema and then we feed it to the search.

Agreed!

> Did you work with celery before?

I use it daily at work. It's pretty much the defacto standard in the python world because the API is simple and it scales well. Seen it at many other python shops before.

**Comment by lwm** [comment]
> Found another free content parser: https://www.readability.com/developers/api/parser

Great! I didn't have the idea of content parsers in my head ... let's definitely integrate.

**Comment by dev-tim** [comment]
@lwm Ok, then should we use http://scrapy.org/ as actual scraper in the worker? Or you have something better in mind?

**Comment by lwm** [comment]
> @lwm Ok, then should we use http://scrapy.org/ as actual scraper in the worker?

I was assuming we would although I never used it before.

On review, it seems to already provide what I described above, baked in. Check [the architecture][2].

Also, it has some nice [deployment options][1].

This means, we could delegate *a lot* of responsibility to `scrapy`.

I will post a clear overview (via diagram) of how I expect things to work from tonights meetup.

[1]: http://doc.scrapy.org/en/latest/topics/deploy.html#topics-deploy
[2]: http://doc.scrapy.org/en/latest/topics/architecture.html

**Comment by oliversauter** [comment]
@lwm 
>>Found another free content parser: https://www.readability.com/developers/api/parser
>Great! I didn't have the idea of content parsers in my head ... let's definitely integrate.

Newspaper3k we currently use is a content parser as well, right?

Actually we have multiple options: Scrapy, Newspaper3k, Boilerpipe (all open source/python) and the readability parser. What they do is taking a URL and extracting content. When we talk about parser, we are talking about this right?

>>I will post a clear overview (via diagram) of how I expect things to work from tonights meetup.
GREAT!

>> This means, we could delegate a lot of responsibility to scrapy.
Scrapy might not always be the best choice, nor are the others. We might implement some logic that allows us to prescan a few URLs from each domain with each parser, and then decide on the basis of the resulting content, which parser we should continue to use for the specific domain.

**Comment by oliversauter** [comment]
@lwm @dev-tim 

We might have multiple DB types dependent on the content we crawl. 
For example facebook data we might have to store into a graph DB. (whereas articles themselves in a sql)
I did some research on the GraphAPI yesterday and wooaaah(!) we can get so much nice content out of that!

**Comment by lwm** [comment]
@oliversauter 

> Newspaper3k we currently use is a content parser as well, right?

Correct.

> What they do is taking a URL and extracting content. 
> When we talk about parser, we are talking about this right?

We are specifically talking about is the extracting and [munging][2] of the content. 
Consuming the URL happens earlier in the pipeline.

> Actually we have multiple options: Scrapy, ...

Scrapy is actually a crawler/parser *framework*. So, things like the readability API, Newspaper3k Boilerpipe are just one component of what Scrapy can offer. We can also mix these parsers to match what we find the best.

> We might have multiple DB types dependent on the content we crawl. 

This might well be the case. We need to carefully draft the service landscape tonight to see how we want to proceed here. We don't want to introduce too many moving parts so early on.

Also, you asked before: How to not get our crawler banned.  Well, [here][1] seems to be all the pointers we need.

[1]: http://doc.scrapy.org/en/latest/topics/practices.html#avoiding-getting-banned
[2]: https://www.quora.com/What-is-data-munging

**Comment by oliversauter** [comment]
> This might well be the case. We need to carefully draft the service landscape tonight to see how we want to proceed here. We don't want to introduce too many moving parts so early on.

Yes totally, tonight is just about the news content crawler itself.

**Comment by oliversauter** [comment]
#### Based on our chats from yesterday here the pipeline for the crawler
This was the scribble of the pipeline for the crawler we came up yesterday. (will put it in a collaborative digital diagram with Gliffy as soon as we converge on the setup)

![img_6086](https://cloud.githubusercontent.com/assets/7870039/16583598/eaa2d14c-42b6-11e6-8716-1ee3c8385d0d.jpg)

 1. **The Crawler input is a list of domains**
 2. **The linkchecker indexes all URLs under each domain**
  - Needs to be multithreaded (Multiple domains crawled at the same time)
  - Needs to throw out all URLs with:
     - Querystring
     - More than 200 characters
     - The filtering must be done **within the scrapy process itself** to avoid unnecessary crawling time.** You can definitely change the scrapy settings to manage this. 
  - Needs to log all possible errors
     - Failed domain
     - Failed URL
 3. **Linkcleaner gets each URL and removes URLs that are unlikely to be articles.**
   - Direct or batch processing? I assume there is no reason why we could not do direct processing because it involves 2 lines of code to do so. 
   - Example for non article: {"url": "https://www.biofortified.org/category/food/"},
   - Needs to throw out all URLs that have certain strings in it (ie. "/category/" , "/tag" , ".jpg" etc.)
   - Needs to take expandable List of strings, so we can adapt better 
   - Needs to save all URLS **that are sorted out** into some file (does not need to be db)
 4. **HTML Parser: Just parsers HTML code of URL and save it to DB**
   - So we can try the effectiveness of different parsers without reparsing from the web in the next step
   - Maybe saving it to InternetArchive.org?
 5. **Parser logic** 
   - Parser logic parses the different elements (title, text, keywords etc) with every parser we have to test their effectiveness of content extraction for each domain. This parser can then be used as defacto standards. If it is not to ressource intensive, we could also think about just parsing every HTML with every parser everytime to take the one result with the most data to save. 
     - Boilerpipe
     - BeautifulSoup
     - Newspaper3k
     - Readability 
   - Outputs a JSON File and sends it to [Logic](https://github.com/WorldBrain/Webmarks/issues/16#issuecomment-230454703) 
 6. **Logic saves all data to PostgreSQL(?) with columns**
    - Title
    - Text
    - Keywords
    - NLP
    - Summary
    - Publish Date
    - tags
    - urls
    - authors
    - domainname
    - parse_time
    -  other???
 
## Questions to resolve

- [ ] What framework do we use for logging errors?
- [ ] What best practices are there to not be banned? (robot.txt. waiting time etc)
- [ ] How do we stay updated when new articles coming out on a domain? Attaching to the RSS feeds of each domain? Recrawling?
- [ ] Other column we should save in the final step?

**Comment by lwm** [comment]
Nice.

> What framework do we use for logging errors?

We'll most likely use the [Python stdlib logger][1]. We can also use [scrapy's one][2].

> What best practices are there to not be banned? (robot.txt. waiting time etc)

We can follow [scrapy's guidelines][3] as a first step.

> Attaching to the RSS feeds of each domain?

Good idea! Not always available though ... we'll need to figure that out ...

> Other column we should save in the final step?

I suppose this is going to be more clear when @arsenal9971 / whoever starts to work on parsing.

[1]: https://docs.python.org/3/library/logging.html
[2]: http://doc.scrapy.org/en/latest/topics/logging.html
[3]: http://doc.scrapy.org/en/latest/topics/practices.html#avoiding-getting-banned
[4]: http://cachedview.com/

**Comment by oliversauter** [comment]
> We'll most likely use the Python stdlib logger. We can also use scrapy's one.

Do you need more input to decide (from whom)? (how easy is it to later change this?) If your are confident that it does the trick, lets converge on that. 

> We can follow scrapy's guidelines as a first step.

Ok I assume you do the implementation of that as well. 

>> Attaching to the RSS feeds of each domain?

Needs to be a separate updater process then I assume?

> I suppose this is going to be more clear when @arsenal9971 / whoever starts to work on parsing.

The information I listed is more or less all we get from the parsing itself. (at least from newspaper)
Is there anything you can think of that we need to save for ourselves? (like parse_time)

**Comment by lwm** [comment]
> Do you need more input to decide (from whom)? (how easy is it to later change this?) If your are confident that it does the trick, lets converge on that.

I'm confident in it. Anyone can suggest changes, should be easy to change.

> Needs to be a separate updater process then I assume?

Yes, this will be somehow under the control of the web server that will run concurrent jobs. 

> Is there anything you can think of that we need to save for ourselves? (like parse_time)

Not sure. We can figure it out later anyway

**Comment by oliversauter** [comment]
http://www.programmableweb.com/news/195-science-apis-springer-epa-and-ncbi/2012/03/28

Woah! :) A lot to use!

**Comment by arsenal9971** [comment]
That's amazing

**Comment by lwm** [comment]
I think we have achieved a clear idea of the pipeline now. 

Any unresolved questions can come again in more fine grained issues.

**Comment by oliversauter** [comment]
I think we should rediscuss this in terms of how we would use scrapinghub to do the job. For now that seems to be the most reasonable option, since we would not have to care about all the "not being banned" logic and so forth. It would be simple API calls and it is not too expensive to use either. 

Since we have now the server costs covered for now, we could spend parts the 50-80 bucks budget/month on their service.

**Comment by lwm** [comment]
> Since we have now the server costs covered for now, we could spend parts the 50-80 bucks budget/month on their service. 

Sounds solid!
